DAPP/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('gestion.urls')),
    path('training', include('training.urls')),
    path("admin/", admin.site.urls),
    path('auth/', include('authentification.urls')),

]

gestion/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'gestion'


urlpatterns = [
    
    path('', views.home, name='home'),
    path('profil/', views.profil, name='profil'),
    path('custom_404/', views.custom_404, name='custom_404'),
    path('diagramme/', views.diagramme, name='diagramme'),

    path('create_player/', views.create_player, name='create_player'),
    path('create_team/', views.create_team, name='create_team'),
    path('player_list/', views.player_list, name='player_list'),
    path('team_list/', views.team_list, name='team_list'),


    path('team_detail/<int:team_id>/', views.team_detail, name='team_detail'),
    path('update_formation_player/', views.update_formation_player, name='update_formation_player'),

    path('player_detail/<int:player_id>/', views.player_detail, name='player_detail'),
    path('diagramme/<int:player_id>/', views.diagramme, name='diagramme'),


    path('manage_trading/<int:trading_id>/', views.manage_trading, name='manage_trading'),
    path('trading_list/', views.trading_list, name='trading_list'),
    path('propose_trading/<int:player_id>/', views.propose_trading, name='propose_trading'),
    path('accept_trading/<int:trading_id>/', views.accept_trading, name='accept_trading'),

    path('messagerie/', views.messagerie, name='messagerie'),
    path('create_message/', views.create_message, name='create_message'),
    path('delete_message/<int:message_id>/', views.delete_message, name='delete_message'),
    path('confirm_delete_message/<int:message_id>/', views.confirm_delete_message, name='confirm_delete_message'),
     path('messagerie/delete_selected/', views.delete_selected_messages, name='delete_selected_messages'),

    path('message_detail/<int:messagerie_id>/', views.message_detail, name='message_detail'),
    path('response_message/<int:receiver_id>/<int:trading_number>/<int:message_id>/', views.response_message, name='response_message'),
    
]

training/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'training'


urlpatterns = [
    
    path('/<int:player_id>', views.training, name='training'),


    
]

gestion/forms.py
# forms.py (dans l'application "gestion")
from django import forms
from .models import Player, Trading, Team,Messagerie,Profil
from django.contrib.auth.models import User 
from django_select2.forms import ModelSelect2Widget

class PlayerForm(forms.ModelForm):
    player_team = forms.ModelChoiceField(queryset=Team.objects.all(), label='Équipe')
    class Meta:
        model = Player
        fields = ['name', 'value',  'player_team', 'price']  # Ajoutez d'autres champs au besoin
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['value'].widget = forms.NumberInput(attrs={'step': 10000})

class TradingForm(forms.ModelForm):
    class Meta:
        model = Trading
        fields = ['proposed_value']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['proposed_value'].widget = forms.NumberInput(attrs={'step': 10000})

class TeamForm(forms.ModelForm):
    team_name = forms.CharField(max_length=100)  # Champ de nom d'équipe distinct

    class Meta:
        model = Team
        fields = ['team_name']  # Ajoutez d'autres champs au besoin
class ProfilForm(forms.ModelForm):
    profil_name = forms.CharField(max_length=100)  # Champ de nom de profil distinct

    class Meta:
        model = Profil
        fields = ['profil_name']  # Ajoutez d'autres champs au besoin
class ComposeInitialMessageForm(forms.Form):
    #receiver = forms.CharField(widget=forms.Textarea,label='Receiver'),
    receiver = forms.CharField(max_length=50, label='To')
    subject = forms.CharField(max_length=100, label='Subject')
    text = forms.CharField(widget=forms.Textarea,max_length=1000, label='Text')





class ComposeMessageForm(forms.Form):
    receiver = forms.ModelChoiceField(queryset=User.objects.all(),label='Receiver',widget=ModelSelect2Widget(model=User,search_fields=['username__icontains'],)),
    subject = forms.CharField(max_length=100, label='Subject')
    text = forms.CharField(widget=forms.Textarea, label='Message')
    #trading_number = forms.IntegerField(label='Trading Number')
    #proposed_amount = forms.DecimalField(max_digits=10, decimal_places=0, label='Proposed Amount')
    def clean_receiver(self):
        receiver_name = self.cleaned_data.get('receiver')
        try:
            receiver_team = Team.objects.get(name=receiver_name)
        except Team.DoesNotExist:
            raise forms.ValidationError("L'équipe spécifiée n'existe pas.")
        return receiver_name

class DeleteMessagesForm(forms.Form):
    selected_messages = forms.ModelMultipleChoiceField(
        queryset=Messagerie.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

class DeleteMessagesForm(forms.Form):
    selected_messages = forms.ModelMultipleChoiceField(
        queryset=Messagerie.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

gestion/views.py
# Vues (views.py)
from django.shortcuts import render, redirect, get_object_or_404
from .models import Trading, Player,Team, Messagerie, Profil, Formation
from .forms import PlayerForm, TradingForm,ComposeMessageForm,ComposeInitialMessageForm, DeleteMessagesForm, ProfilForm, TeamForm,DeleteMessagesForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.contrib import messages
from django.http import HttpResponseNotFound
from .tests import generate_offensive_player_profile,generate_random_birthdate,generate_defensive_player_profile,generate_goalkipper_player_profile
from datetime import datetime
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import random
from .heptagone import coordonnes_point
from django.db.models import Q
from django.http import JsonResponse
import json

def custom_404(request, exception):
    return render(request, '404.html', status=404)

def diagramme(request):
    player = Player.objects.all().first()
    A_HEPTAGONE_X = 200
    A_HEPTAGONE_Y = 0
    positions= coordonnes_point(0.8, player.general, player.attaque, player.defense,player.attaque, player.general,player.defense, player.attaque)
    liste_x = []
    liste_y = []
    for i in range(7):
        print(positions[i])
        liste_x.append(positions[i][0])
        liste_y.append(positions[i][1])
        print(liste_x[i])
        print(liste_y[i])
    AX,BX,CX,DX,EX,FX,GX = liste_x[0],liste_x[1],liste_x[2],liste_x[3],liste_x[4],liste_x[5],liste_x[6]
    AY,BY,CY,DY,EY,FY,GY = liste_y[0],liste_y[1],liste_y[2],liste_y[3],liste_y[4],liste_y[5],liste_y[6]
    points = [
    {"x": A_HEPTAGONE_X, "y": A_HEPTAGONE_Y  -20},

    ]
    return render(request, 'diagramme.html', {'points':points,'AX': AX, 'BX':BX,'CX':CX, 'DX':DX, 'EX':EX, 'FX':FX, 'GX':GX, 'AY':AY, 'BY':BY, 'CY':CY, 'DY':DY, 'EY':EY, 'FY':FY, 'GY':GY})

def home(request):   

    team = Team.objects.all()
    team = random.choice(team)
    player_profile = generate_offensive_player_profile()
    date_obj = datetime.strptime(player_profile['Birthday'], "%d/%m/%Y")
    
    player = Player(nationnality=player_profile['Nationnality'], name=player_profile['Name'],second_name=player_profile['Second_name'],player_team=team,value=player_profile['Value'],price=0,date_de_naissance=date_obj,size=player_profile['taille'],weight=player_profile['poids'],feet=player_profile['Feet'], style=player_profile['Style'],main_position=player_profile['Poste'],general=player_profile['General'],attaque=player_profile['Attaque'],defense=player_profile['Defense'],vitesse = player_profile['Vitesse'],interception=player_profile['Interception'], passe=player_profile['Passe'], mental=player_profile['Mental'],physique=player_profile['Physique'])
    print("Playe r1 main position-----------",player.main_position )
    player.save()
    team = Team.objects.all()
    team = random.choice(team)
    player_profile = generate_defensive_player_profile()
    date_obj = datetime.strptime(player_profile['Birthday'], "%d/%m/%Y")
    player = Player(nationnality=player_profile['Nationnality'],name=player_profile['Name'],second_name=player_profile['Second_name'],player_team=team,value=player_profile['Value'],price=0,date_de_naissance=date_obj,size=player_profile['taille'],weight=player_profile['poids'],feet=player_profile['Feet'], style=player_profile['Style'],main_position=player_profile['Poste'],general=player_profile['General'],attaque=player_profile['Attaque'],defense=player_profile['Defense'],vitesse = player_profile['Vitesse'],interception=player_profile['Interception'], passe=player_profile['Passe'], mental=player_profile['Mental'],physique=player_profile['Physique'])
    player.save()


    return render(request, 'home.html')

@login_required(login_url='/auth/inscription/')
def profil(request):
    profil = Profil.objects.filter(user_profil=request.user).first()
    team_form = TeamForm()
    profil_form = ProfilForm()

    if request.method == 'POST':
        if profil and not profil.team_profil:
            # Si un profil existe mais pas d'équipe, associez l'équipe au profil
            team_form = TeamForm(request.POST)
            if team_form.is_valid():
                team_name = team_form.cleaned_data['team_name']
   
                team = Team(name=team_name, owner=request.user, budget=50000)
                team.save()

                profil.team_profil = team
                profil.save()

                return redirect('gestion:profil')
        else:
            # Si ni un profil ni une équipe n'existent, créez-les
            team_form = TeamForm(request.POST)
            profil_form = ProfilForm(request.POST)
            if team_form.is_valid() and profil_form.is_valid():
                team_name = team_form.cleaned_data['team_name']
        
                team = Team(name=team_name, owner=request.user, budget=50000)
                team.save()
                profil_name = profil_form.cleaned_data['profil_name']
                profil = Profil(name=profil_name, user_profil=request.user, team_profil=team)
                profil.save()
                formation = Formation(name="Formation1", team=team)
                formation.save()
                return redirect('gestion:profil')

    return render(request, 'profil.html', {'team_form': team_form, 'profil_form': profil_form, 'profil': profil })


#Messagerie---------------------------------------------------------------
@login_required(login_url='/auth/inscription/')
def messagerie(request):
    user = request.user
    status_filter = request.GET.get('status')
    from_filter = request.GET.get('from')
    trading_number_filter = request.GET.get('trading_number')
    delete_form = DeleteMessagesForm(request.POST or None)
    
    messages = Messagerie.objects.filter(recever=user)
    
    if request.method == 'POST':
        if 'delete_selected' in request.POST:
            delete_form = DeleteMessagesForm(request.POST)
            if delete_form.is_valid():
                selected_messages = delete_form.cleaned_data.get('selected_messages')
                if selected_messages:
                    Messagerie.objects.filter(id__in=selected_messages).delete()
    
    if status_filter == 'unread':
        messages = messages.filter(status='non lus')
    elif status_filter == 'read':
        messages = messages.filter(status='lus')
    elif status_filter == 'replied':
        messages = messages.filter(status='repondu')
    
    if from_filter:
        messages = messages.filter(sender__username__icontains=from_filter)
    
    if trading_number_filter:
        messages = messages.filter(trading_number_id=trading_number_filter)
    
    return render(request, 'messagerie.html', {
        'messages': messages,
        'status_filter': status_filter,
        'from_filter': from_filter,
        'trading_number_filter': trading_number_filter,
        'delete_form': delete_form,  # Passer le formulaire au modèle
    })

@login_required(login_url='/auth/inscription/')
def message_detail(request, messagerie_id):
    message = get_object_or_404(Messagerie, pk=messagerie_id)
    message.status = 'lus'
    message.save()
    trading = message.trading_number
    
    
    return render(request, 'message_detail.html', {'message': message, 'trading':trading})
@login_required(login_url='/auth/inscription/')
def create_message(request):
    if request.method == 'POST':
        form = ComposeInitialMessageForm(request.POST)
        if form.is_valid():
            sender = request.user
            text = form.cleaned_data['text']
            subject = form.cleaned_data['subject']
            receiver_name = form.cleaned_data['receiver']

            try:
                # Vérifiez si l'équipe spécifiée dans le champ "From" existe
                receiver_team = Team.objects.get(name=receiver_name)

                # Créez le message avec l'équipe en tant que destinataire
                message = Messagerie(sender=sender, status='non lus', recever=receiver_team.owner, subject=subject, text=text, trading_number=None)
                message.save()

                return redirect('gestion:messagerie')

            except Team.DoesNotExist:
                # L'équipe spécifiée n'existe pas, ajoutez une erreur au formulaire
                form.add_error('receiver', "L'équipe spécifiée n'existe pas.")
    else:
        form = ComposeInitialMessageForm()

    return render(request, 'response_message.html', {'form': form})

def confirm_delete_message(request, message_id):
    message = Messagerie.objects.get(pk=message_id)
    if request.method == "POST":
        # Traitez la logique de suppression ici
        message.delete()
        return redirect('gestion:message_deleted')  # Redirigez vers la page de confirmation de suppression

    return render(request, 'confirm_delete_message.html', {'message_id': message_id})
@login_required(login_url='/auth/inscription/')
def delete_message(request, message_id):
    
    message = Messagerie.objects.get(id=message_id)
    message.delete()

    return redirect('gestion:messagerie')
@login_required(login_url='/auth/inscription/')
def delete_selected_messages(request):
    if request.method == 'POST':
        delete_form = DeleteMessagesForm(request.POST)
        if delete_form.is_valid():
            selected_messages = delete_form.cleaned_data['selected_messages']
            Messagerie.objects.filter(id__in=selected_messages).delete()
    return redirect('gestion:messagerie')
@login_required(login_url='/auth/inscription/')
def response_message(request, receiver_id, trading_number,message_id):
   
    receiver = User.objects.get(id=receiver_id)  # Assurez-vous d'importer le modèle User
    trading = Trading.objects.get(id=trading_number)
    player = trading.player
    
    initial_data = {
        'receiver': receiver,
        'subject': '',
        'trading_number': trading_number,
        
    }

gestion/templates/confirm_delete_message.html
{% extends 'base.html' %}

{% block content %}
<style>
    /* Styles pour la boîte de confirmation */
    .confirm-dialog {
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background-color: #fff;
        padding: 20px;
        border: 1px solid #ccc;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
        z-index: 1000;
        text-align: center; /* Centre le texte */
    }

    /* Styles pour les boutons */
    .delete-button {
        background-color: #e21d1d;
        color: white;
        padding: 5px 10px;
        border: none;
        border-radius: 4px;
        text-decoration: none;
        font-weight: bold;
        margin-right: 10px;
    }

    .delete-button:hover {
        background-color: #b31b01;
    }

    .no-button {
        background-color: #3498db;
        color: white;
        padding: 5px 10px;
        border: none;
        border-radius: 4px;
        text-decoration: none;
        font-weight: bold;
    }

    .no-button:hover {
        background-color: #2980b9;
    }
</style>

<div class="confirm-dialog">
    <h2>Confirm Message Deletion</h2>
    <p>Are you sure you want to delete this message?</p>
    <form method="post" action="{% url 'gestion:delete_message' message_id=message_id %}">
        {% csrf_token %}
        <button type="submit" class="delete-button">Delete</button>
        <a href="{% url 'gestion:messagerie' %}" class="no-button">Cancel</a>
    </form>
</div>
{% endblock %}

gestion/templates/create_player.html
{% extends 'base.html' %}



{% block content %}
<h1>Create Player</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
</form>
{% endblock %}

gestion/templates/create_team.html
{% extends 'base.html' %}



{% block content %}
<h1>Create Team</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Create</button>
</form>
{% endblock %}

gestion/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
 
    
    {% if message %}
        <div id="message" class="alert alert-info">{{ message }}</div>
    {% endif %}
    <div class="game-menu">
        <h1>Bienvenue {{request.user}}</h1>
        <h1>Menu</h1>
        <a href="{% url 'gestion:profil' %}" class="game-menu-item">Start</a>

    </div>



{% endblock %}

{% block javascript %}
    <script>
        // Masquer la notification après 5 secondes
        setTimeout(function() {
            document.getElementById('message').style.display = 'none';
        }, 5000);
    </script>
{% endblock %}

gestion/templates/message_detail.html
<style>
    /* Ajoutez le style CSS ici */
    .message-detail {
        background-color: #fff;
        border: 1px solid #ddd;
        border-radius: 4px;
        padding: 20px;
        margin: 20px auto;
        max-width: 600px;
        box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.1);
    }

    .message-detail h2 {
        font-size: 24px;
        margin-bottom: 10px;
    }

    .message-detail p {
        font-size: 16px;
        margin: 5px 0;
    }

    .message-detail strong {
        font-weight: bold;
    }

    .message-detail hr {
        border: none;
        border-top: 1px solid #ddd;
        margin: 15px 0;
    }

    .message-detail p:last-child {
        margin-bottom: 0;
    }
    .new-message-button {
        display: inline-block;
        background-color: #3498db;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 4px;
        text-decoration: none;
        font-weight: bold;
        margin-bottom: 10px;
    }

    .new-message-button:hover {
        background-color: #2980b9;
    }
    .delete-button {
        display: inline-block;
        background-color: #fc0d0d;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 4px;
        text-decoration: none;
        font-weight: bold;
        margin-bottom: 10px;
    }

    .delete-button:hover {
        background-color: #970404;
    }

    /* Ajoutez des styles pour le bouton "Répondre" si nécessaire */
</style>

{% extends 'base.html' %}


    {% block content %}
    <h1>Message Detail</h1>
    <p><strong>From:</strong> {{ message.sender }}</p>
    <p><strong>To:</strong> {{ message.recever }}</p>
    <p><strong>Date:</strong> {{ message.date }}</p>
    <hr>
    <p>{{ message.text }}</p><br>
    <td><a href="{% url 'gestion:confirm_delete_message' message_id=message.id %}" class="delete-button" onclick="return confirmDelete(this);"> Delete</a></td>

    {% if message.trading_number %}

    {% if trading.status_trading == 'pending' or trading.status_trading == 'proposed'  %}
            <a href="{{ message.get_reply_link }}" class="new-message-button">Répondre</a>      
            <a href="{% url 'gestion:manage_trading' trading_id=message.trading_number.id %}" class="new-message-button">Manage trading</a>
        {% endif %}  
    {% endif %}
    

{% endblock %}

gestion/templates/profil.html
{% extends 'base.html' %}

{% block content %}
<div class="profil-name">

    {% if profil %}
    <div class="profil-content">
        <h1 class="profil-header">Profil de {{profil}}</h1>
        <hr>
        <h2 class="team-name">Team Name : {{profil.team_profil}}<br> <a href="{% url 'gestion:team_detail' team_id=profil.team_profil.id %}" class="my-button">Détail Team</a></h2>
        <br>
  
        <p class="note-effectif">Note general : {{profil.team_profil.get_general}}</p>
        <p class="budget">Budget : {{profil.team_profil.budget}} euros</p>
        <p class="date-creation">Date de Création : 1915</p>
        <p class="nombres-joueurs">Nombre de Joueurs : {{profil.team_profil.get_total_players}}</p>
        
        <p class="valeur-effectif">Valeur de l'Effectif : {{profil.team_profil.get_total_value}} euros</p>

    </div>
    {% endif %}
    {% if not profil %}
    <form method="post">
        {% csrf_token %}
        <h1 class="profil-header">Create Profile</h1>
    
        <!-- Include the Profil Name field for creating a profile -->
        {{ profil_form.profil_name.label_tag }} {{ profil_form.profil_name }}
    
        <!-- Include the Team Name field for creating a team -->
        {{ team_form.team_name.label_tag }} {{ team_form.team_name }}
    
        <button type="submit" class="my-button">Create Profile</button>
    </form>
    {% endif %}
    <div class="create-team">
        {% if profil and not profil.team_profil %}
        <form method="post">
            {% csrf_token %}
            <h1 class="team-create-header">Create Team</h1>
    
            <!-- Include the Team Name field for creating a team -->
            {{ team_form.team_name.label_tag }} {{ team_form.team_name }}
    
            <button type="submit" class="my-button">Create Team</button>
        </form>
        {% endif %}

    </div>
    
  
    
</div>


<style>
    /* Styles pour le contenu du profil */
    .profil-content {
        background-color: #f5f5f5;
        padding: 68px;
        border-radius: 15px;
        margin-top: 20px;
    }

    .profil-header {
        font-size: 44px;
        margin-bottom: 10px;
    }

    .team-name {
        font-size: 38px;
        font-weight: bold;
    }
    .note-effectif,
    .budget,
    .date-creation,
    .nombres-joueurs,
    .valeur-effectif {
        font-size: 26px;
        margin: 10px 0;
    }

    /* Styles pour le formulaire */
    .team-create-header {
        font-size: 24px;
        margin-top: 20px;
    }

    /* Style pour le bouton personnalisé */
    .my-button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #3498db;
        color: white;
        text-decoration: none;
        border-radius: 5px;
        font-weight: bold;
        margin-top: 10px;
    }

    .my-button:hover {
        background-color: #2980b9;
    }
</style>

{% endblock %}

gestion/templates/team_list.html
<style>
.team-list {
    background-color: #f5f5f5;
    border: 1px solid #ddd;
    border-radius: 4px;
    padding: 20px;
}

.team-list h1 {
    font-size: 24px;
    margin-bottom: 10px;
}

.team-list-items {
    list-style: none;
    padding: 0;
}

.team-item {
    border: 1px solid #ddd;
    border-radius: 4px;
    padding: 10px;
    margin-bottom: 10px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    background-color: #fff;
}

.team-name {
    font-weight: bold;
}

.team-detail-link {
    background-color: #3498db;
    color: white;
    padding: 5px 10px;
    border: none;
    border-radius: 4px;
    text-decoration: none;
}

.no-teams {
    font-style: italic;
    color: #666;
}













</style>

{% extends 'base.html' %}

{% block content %}

<div class="team-list">
    <h1>Team List</h1>
    {% if teams %}
    <ul class="team-list-items">
        {% for team in teams %}
        <li class="team-item">
            <span class="team-name">{{ team.name }}</span>
            <span class="team-name">Europe</span>
            <a href="{% url 'gestion:team_detail' team_id=team.id %}" class="team-detail-link">Detail {{ team.name }}</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p class="no-teams">Aucune équipe</p>
    {% endif %}
</div>

{% endblock %}

gestion/templates/trading_list.html
{% extends 'base.html' %}

{% block content %}
<style>
    table {
        border-collapse: collapse;
        width: 100%;
        border: 1px solid #ddd;
    }

    th, td {
    text-align: left;
    padding: 8px;
    width: 8%; /* Ajustez la largeur selon vos besoins */
}

    th {
        background-color: #f2f2f2;
    }

    .status-pending {
        color: green;
    }

    .status-closed {
        color: red;
    }

    .table-header {
        background-color: #333;
        color: rgb(0, 0, 0);
    }

    .table-header th {
        padding: 10px;
    }

    .table-content td {
        border-bottom: 1px solid #ddd;
    }

    .table-content tr:last-child td {
        border-bottom: none;
    }

</style>

<h2>Your Trading List:</h2>
<p>Sort by:
    <a href="{% url 'gestion:trading_list' %}?sort_by=status{% if status_accepted %}&status_accepted=1{% endif %}{% if status_rejected %}&status_rejected=1{% endif %}{% if status_pending %}&status_pending=1{% endif %}{% if status_closed %}&status_closed=1{% endif %}{% if status_proposed %}&status_proposed=1{% endif %}">Status</a> |
    <a href="{% url 'gestion:trading_list' %}?sort_by=price{% if status_accepted %}&status_accepted=1{% endif %}{% if status_rejected %}&status_rejected=1{% endif %}{% if status_pending %}&status_pending=1{% endif %}{% if status_closed %}&status_closed=1{% endif %}{% if status_proposed %}&status_proposed=1{% endif %}">Price</a>
</p>


<form method="get">
    <label for="status_filter">Filter by Status:</label>
    <input type="checkbox" id="status_accepted" name="status_accepted" {% if status_accepted %}checked{% endif %}>
    <label for="status_accepted">Accepted</label>
    <input type="checkbox" id="status_rejected" name="status_rejected" {% if status_rejected %}checked{% endif %}>
    <label for="status_rejected">Rejected</label>
    <input type="checkbox" id="status_pending" name="status_pending" {% if status_pending %}checked{% endif %}>
    <label for="status_pending">Pending</label>
    <input type="checkbox" id="status_closed" name="status_closed" {% if status_closed %}checked{% endif %}>
    <label for="status_closed">Closed</label>
    <input type="checkbox" id="status_proposed" name="status_proposed" {% if status_proposed %}checked{% endif %}>
    <label for="status_proposed">Proposed</label>
    <button type="submit">Apply Filters</button>
</form>
<table class="table-header">
    <tr>
        <th>Trading ID</th>
        <th>Buyer</th>
        <th>Seller</th>
        <th>Player</th>
        <th>Proposed Value</th>
        <th>Status</th>
        <th>Action</th>
    </tr>
</table>
<table class="table-content">
    <tr>
        <td colspan="7"><h2>Buy Trading :</h2></td>
    </tr>
    
    {% for trading in buyer_tradings %}
  
        <tr>
            <td>{{ trading.id }}</td>
            <td>{{ trading.buyer.username }}</td>
            <td>{{ trading.player.player_team.owner }}</td>
            <td>{{ trading.player.name }}</td>
            <td>${{ trading.proposed_value }} euros</td>
            <td class="{% if trading.status_trading == 'pending' %}status-pending{% elif trading.status_trading == 'rejected' %}status-closed{% endif %}">
                {{ trading.status_trading }}
            </td>
            <td>
                {% if trading.status_trading != 'rejected' %}
                    <a href="{% url 'gestion:manage_trading' trading_id=trading.id %}">Manage trading</a>
                {% endif %}
            </td>
        </tr>
   
    {% endfor %}
    
    <tr>
        <td colspan="7"><h2>Sell Trading :</h2></td>
    </tr>
    {% for trading in seller_tradings %}
        <tr>
            <td>{{ trading.id }}</td>
            <td>{{ trading.buyer.username }}</td>
            <td>{{ trading.seller.username }}</td>
            <td>{{ trading.player.name }}</td>
            <td>${{ trading.proposed_value }} euros</td>
            <td class="{% if trading.status_trading == 'pending' %}status-pending{% elif trading.status_trading == 'rejected' %}status-closed{% endif %}">
                {{ trading.status_trading }}
            </td>
            <td>
                {% if trading.status_trading != 'rejected' %}
                    <a href="{% url 'gestion:manage_trading' trading_id=trading.id %}">Manage trading</a>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
</table>
{% endblock %}