DAPP/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('gestion.urls')),
    path('training', include('training.urls')),
    path("admin/", admin.site.urls),
    path('auth/', include('authentification.urls')),

]

authentification/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'authentification'


urlpatterns = [

    path('inscription/', views.inscription, name='inscription'),
    path('login/', views.user_login, name='user_login'),

    path('logout/', views.user_logout, name='user_logout'),

    
]

authentification/models.py
from django.db import models

# Create your models here.

authentification/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

class LoginForm(forms.Form):
    username = forms.CharField(label="Nom d'utilisateur")
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput)

authentification/views.py
from django.shortcuts import render, redirect
from .forms import NewUserForm,LoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


def inscription(request):
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            # Faites ce que vous voulez après l'inscription, par exemple, connecter l'utilisateur
            return redirect('authentification:user_login')  # Redirige vers la page d'accueil après inscription
    else:
        form = NewUserForm()
    return render(request, 'inscription.html', {'form': form})


def user_login(request):
    form = LoginForm(request.POST)
    message = 'bonjour'
    print('step1')
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
            )
            print('step2')
            if user is not None:
                login(request, user)
                message = f'Hello {user.username}! You have been logged in'
                print('step3')
                return redirect('gestion:home')
            else:
                message = 'Login failed!'
    return render(request, 'login.html', context={'form': form, 'message': message})


@login_required
def user_logout(request):
    logout(request)
    return redirect('gestion:home')

authentification/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Accueil</title>
</head>
<body>
    <h2>Accueil</h2>
    
    {% if request.user.is_authenticated %}
    <p>Bonjour, {{ request.user.username }}! Vous êtes connecté.</p>
    <a href="{% url 'authentification:user_logout' %}">Déconnexion</a>
    {% else %}
    <p>Bienvenue sur notre site. Veuillez vous connecter.</p>
    <a href="{% url 'authentification:user_login' %}">Connexion</a>
    {% endif %}
    <h2>Liste des Utilisateurs</h2>
    <ul>
        {% for user in users %}
            <li>{{ user.username }}__________ {{ user.password }}</li>
        {% endfor %}
        <p>Votre IP de conenxion est : {{user_ip}}</p>
    </ul>
</body>
</html>

authentification/templates/inscription.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Inscription</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="center-form">
        <h2>Inscription</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">S'inscrire</button>
        </form>
    </div>
</body>
</html>

authentification/templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

</head>
<body>

    

    <form method="post">
        
        {% csrf_token %}
        <div class="center-form">
            <h2>Login</h2>
            {{ form.as_p }}
            <button type="submit">Login</button>
        </br>
            <a href="{% url 'authentification:inscription' %}">S'inscrire</a>
        </div>
        
    </form>
    
    </body><br>
    
</body>
</html>